### ISSUE TITLE
ARM NEON/VFP support seems to exist but is disabled by default

### ISSUE THREAD

**Issue by petmac** [unicorn-engine/unicorn#571] opened 2016-06-09 17:17 UTC
Hello,

Sorry if this is a known issue. I searched but didn’t notice it.

I’m trying to emulate an ARM processor with NEON (Cortex-A9). Emulation of the “vpush” instruction failed so I started investigating why.

According to the processor technical reference manual, in order to access VFP and NEON registers, both cp10 and cp11 of CPACR have to be enabled:

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0388f/CIHGHGJE.html

And indeed, when floating point is disabled, QEMU generates an EXCP_UDEF exception in disas_vfp_insn.

When VFP is disabled (ARM_VFP_FPEXC bit 30 is clear), disas_vfp_insn returns failure for instructions like vpush.

Thanks,
Peter

**Comment by aquynh** [comment] 2016-06-10 00:39
can you send a testcase for this (put it under tests/regress/ or tests/unit/), so i can debug this problem?

thanks

**Comment by petmac** [comment] 2016-06-10 06:49
Thanks, I will do that.

I believe the reset state of the CPU is to have FP and VFP disabled, so I don't think it's a bug. It would be nice though to be able to enable them programmatically without having to run code to do it.

**Comment by aquynh** [comment] 2016-06-15 16:58
have you seen this issue yet? https://github.com/unicorn-engine/unicorn/issues/446

**Comment by petmac** [comment] 2016-06-15 17:18
Hi,

Sorry, no I didn't notice it. I actually do very similar though. Before I run user programs I run some code to enable FP and VFP.

Thanks for looking into it.

Peter

**Comment by petmac** [comment] 2016-06-15 17:19
I guess it would be nice to be able to set these registers without having to inject ARM/Thumb code to do it.

**Comment by lunixbochs** [comment] 2016-06-15 17:21
Yep, this comes up for me in x86 and mips as well. We definitely need an MSR API, which could just be special constants for reg_write() with an MSR prefix or something (no need to make a separate API function because it already uses opaque types)

**Comment by aquynh** [comment] 2016-06-15 17:29
We can think about how to enable VFP without extra guest code, but for now
can you modify your testcase so it passes?

**Comment by neobrain** [comment] 2016-06-19 23:27
The status of this issue seems a bit unclear to me.

@lunixbochs, have you gotten unicorn to successfully run VFP code? The test merged in #580 does not seem to work for me (throwing an `UC_ERR_FETCH_UNMAPPED` error), but from what was said here I'm not sure whether it's supposed to illustrate how to enable VFP or just to document that this feature does not work in unicorn yet. Have you gotten unicorn to emulate VFP code at all?

For reference, before stumbling across this issue I tried enabling VFP extensions too, using the following ARM code:
```
    uint8_t enable_vfp_code[] = {
        // Setup Coprocessor Access Control Register
        0x50, 0x0f, 0x11, 0xee, // mrc p15, 0, r0, c1, c0, 2
        0x0f, 0x08, 0x80, 0xe3, // orr r0, r0, 0xf0000 # Enable cp10 and cp11
        0x50, 0x0f, 0x01, 0xee, // mcr p15, 0, r0, c1, c0, 2

        0x00, 0x00, 0xf0, 0xef, // IMB (SWI 0xf00000)

        0x40, 0x04, 0xa0, 0xe3, // mov r0, 0x40000000
        0x10, 0x0a, 0xe8, 0xee, // vmsr fpexc, r0
```

**Comment by aquynh** [comment] 2016-06-20 03:56
that testcase passes for me.

even if we add a functionality of initializing VFP in the future, it is no harm to have a proper code to setup that like how the real code still does. other people can also learn from this testcase when they have similar issue.

**Comment by petmac** [comment] 2016-06-20 08:10
It looks like I made a mistake in that test case. I added more code to run, but I didn't update the ending address in the call to emu_start().

https://github.com/unicorn-engine/unicorn/pull/580/commits/d4f0ab7ba833433a96d04dc84d2807d969919334
The 0x1004 should probably be 0x1020?

I don't believe it should throw UC_ERR_FETCH_UNMAPPED, as I think the only memory access it does is to the stack, and SP is set to the end of the mapped region.

I'm new to ARM and Unicorn and I don't use Python often so apologies if I'm making a mess of this.

**Comment by neobrain** [comment] 2016-06-20 10:01
Thanks for your replies! Indeed, the issue with @petmac's test was on my end (messed up my install temporarily). I can confirm that 0x1004 should be replaced with 0x1020, however.

I also got my ARM code working successfully after fixing a bunch of typos. For reference, here is the final code that I run to enable VFP on the target:
```cpp
        // Enable CP10 and CP11
        0x50, 0x0f, 0x11, 0xee, // mrc p15, 0, r0, c1, c0, 2
        0x0f, 0x06, 0x80, 0xe3, // orr r0, r0, 0xf00000
        0x50, 0x0f, 0x01, 0xee, // mcr p15, 0, r0, c1, c0, 2

        // IMB
        0x00, 0x00, 0xf0, 0xef, // IMB (SWI 0xf00000)

        // Enable VFP in FPEXC
        0x40, 0x04, 0xa0, 0xe3, // mov r0, 0x40000000
        0x10, 0x0a, 0xe8, 0xee, // vmsr fpexc, r0

        // Some testing code to make sure it actually worked...
        0x90, 0x3a, 0x00, 0xee // vmov s1, r3
```

**Comment by aquynh** [comment] 2016-06-20 19:26
please send new PR to fix what you found, thanks.

**Comment by aquynh** [comment] 2016-07-10 02:24
problem solved, thanks!

**Closed by aquynh** 2016-07-10 02:24 UTC
