### ISSUE TITLE
Unicorn stop at MIPS branch delay slot will ignore original branch target address

### ISSUE THREAD

**Issue by dark-lbp** [unicorn-engine/unicorn#1411] opened 2021-06-22 06:16 UTC
If Unicorn stoped at MIPS branch delay slot, after resume Unicorn will skip the original branch target address and execute code after branch delay slot.

Reproduce code
```c
#include <unicorn/unicorn.h>

// li $v0, 0; li $v1, 0; beq $v0, $v1, -0x8; nop; nop;
#define MIPS_CODE32 "\x00\x00\x02\x24\x00\x00\x03\x24\xfd\xff\x43\x10\x00\x00\x00\x00\x00\x00\x00\x00"

// memory address where emulation starts
#define ADDRESS 0x1000000

int main(int argc, char **argv, char **envp)
{
  uc_engine *uc;
  uc_err err;
  int r_v0 = 0x0;     // V0 register
  int r_v1 = 0x0;     // V1 register
  int r_pc = 0x0;     // PC register
  printf("Emulate MIPS code\n");

  // Initialize emulator in MIPS-32bit mode
  err = uc_open(UC_ARCH_MIPS, UC_MODE_32|UC_MODE_LITTLE_ENDIAN, &uc);
  if (err != UC_ERR_OK) {
    printf("Failed on uc_open() with error returned: %u\n", err);
    return -1;
  }

  // map 2MB memory for this emulation
  uc_mem_map(uc, ADDRESS, 2 * 1024 * 1024, UC_PROT_ALL);

  // write machine code to be emulated to memory
  if (uc_mem_write(uc, ADDRESS, MIPS_CODE32, sizeof(MIPS_CODE32) - 1)) {
    printf("Failed to write emulation code to memory, quit!\n");
    return -1;
  }

  // emulate code and stop at nop
  err=uc_emu_start(uc, ADDRESS, ADDRESS + sizeof(MIPS_CODE32) - 1, 0, 3);
  if (err) {
    printf("Failed on uc_emu_start() with error returned %u: %s\n",
      err, uc_strerror(err));
  }

  // now print out some registers
  printf("Emulation stop at 0x0x100000c(NOP). Below is the CPU context\n");

  uc_reg_read(uc, UC_MIPS_REG_4, &r_v0);
  uc_reg_read(uc, UC_MIPS_REG_5, &r_v1);
  uc_reg_read(uc, UC_MIPS_REG_PC, &r_pc);
  printf(">>> V0 = 0x%x\n", r_v0);
  printf(">>> V1 = 0x%x\n", r_v1);
  printf(">>> PC = 0x%x\n", r_pc);

  // emulate one more instruction
  err=uc_emu_start(uc, r_pc, ADDRESS + sizeof(MIPS_CODE32) - 1, 0, 1);
  if (err) {
    printf("Failed on uc_emu_start() with error returned %u: %s\n",
      err, uc_strerror(err));
  }

  printf("Emulate one more instruction. Below is the CPU context\n");
  
  uc_reg_read(uc, UC_MIPS_REG_4, &r_v0);
  uc_reg_read(uc, UC_MIPS_REG_5, &r_v1);
  uc_reg_read(uc, UC_MIPS_REG_PC, &r_pc);
  printf(">>> V0 = 0x%x\n", r_v0);
  printf(">>> V1 = 0x%x\n", r_v1);
  printf(">>> PC = 0x%x\n", r_pc);

  if (r_pc == 0x1000010){
    printf("Bug found, pc register should not be 0x1000010. \n");
  }

  uc_close(uc);

  return 0;
}
```

Running result.
```
Emulate MIPS code
Emulation stop at 0x0x100000c(NOP). Below is the CPU context
>>> V0 = 0x0
>>> V1 = 0x0
>>> PC = 0x100000c
Emulate one more instruction. Below is the CPU context
>>> V0 = 0x0
>>> V1 = 0x0
>>> PC = 0x1000010
Bug found, pc register should not be 0x1000010. 
```

**Comment by wtdcode** [comment] 2021-06-22 07:16
Thanks for your issue. I would look into details ASAP.

**Comment by wtdcode** [comment] 2021-07-15 14:31
Confirmed that it's due to unicorn stopping cpu execution too early.

**Comment by wtdcode** [comment] 2021-07-15 16:08
Fixed in UC2. Link to #1217

**Comment by wtdcode** [comment] 2021-10-03 15:17
Closed due to uc2 beta release.

**Closed by wtdcode** 2021-10-03 15:17 UTC
