### ISSUE TITLE
Can arm64 big endian support be added?

### ISSUE THREAD

**Issue by ZakDanger** [unicorn-engine/unicorn#802] opened 2017-04-21 07:24 UTC
I see that recently ARM big endian support was added, nice work @xizhizhang !
I was wondering if you might be able to add the relevant changes for ARM64 big endian support too?

That would then cover pretty much all main cases for arm:
armle, armbe, arm64le and arm64be.

**Comment by aquynh** [comment] 2017-04-21 07:25
afaik, Arm64 does not have big-endian implementation.

**Comment by aquynh** [comment] 2017-04-21 07:33
i mean there is no real hardware for Arm64 big-endian, so there is no reason to emulate it.

**Comment by xorstream** [comment] 2017-04-21 07:47
Hm ok, i've seen various mentions of arm64be though not what hardware it was intended for. Perhaps it is just support that people have added for various things in case something uses arm64be in the future.

I don't know how complex the additions were to add the armbe support, but if they were simple enough it might still be worth it for completeness.

**Comment by aquynh** [comment] 2017-04-21 07:50
yes i dont mind to support that, as long as there is demand.

**Comment by xizhizhang** [comment] 2017-04-24 15:51
yep, I have added ARM64 big endian support too.
Thanks to unicorn and QEMU's good design, it is easy to support big endian.
But I afraid there are still some bugs, since I have not checked all the translate codes if there are some endian issue.

here is my code:
https://github.com/unicorn-engine/unicorn/pull/806

Thanks.

**Comment by xorstream** [comment] 2017-04-25 03:45
thanks @xizhizhang :)

**Comment by aquynh** [comment] 2017-04-25 05:11
merged everything, thanks. i also updated CREDITS.TXT with https://github.com/unicorn-engine/unicorn/commit/3c7e29958b71de1588e5e1ba7019fc6c7c15de14.

**Comment by xorstream** [comment] 2017-04-26 04:22
Ok so today I found some time to test arm64be support with a real ELF file and found that it is not working correctly, It seems that arm64 (aka ARMv8 in Aarch64 mode) only supports little endian instructions but can access data as little or big endian.

You can get a PDF of the ARMv8 Architecture Reference Manual here:
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.aeg0014g/ABCDEFGH.html

Section B2.6 is for Endian support (page 104 onwards).

"Section B2.6.2 Instruction endianness" says:
"In ARMv8-A, A64 instructions have a fixed length of 32 bits and are always little-endian."

"Section B2.6.3 Data endianness" discusses how data endianess is handled

As a test I used some of the prebuild library binaries inside these packs:
https://releases.linaro.org/archive/14.11/components/toolchain/binaries/aarch64_be-none-elf/
Specifically I downloaded the file "gcc-linaro-4.9-2014.11-x86_64_aarch64_be-elf.tar.xz" and extracted "gcc-linaro-4.9-2014.11-x86_64_aarch64_be-elf\lib\gcc\aarch64_be-none-elf\4.9.3\libgcc.a" from it and then extracted "muldi3.o" from "libgcc.a". I used 7zip to do both extractions in windows.


So can we look at altering the arm64be support in unicorn to only deal with data accesses in big endian but instruction accesses in little endian?

**Comment by aquynh** [comment] 2017-04-26 05:53
yes we need to fix the core of arm64 to handle big endian data. 

should we revert these arm64 bigendian commits?

**Comment by xorstream** [comment] 2017-05-02 03:01
I think this is @xizhizhang 's call.
Probably its just a matter of not swapping instruction fetches but still swapping data fetches.

**Comment by xizhizhang** [comment] 2017-05-03 13:58
Yes, we can swap the instructions by just setting dc->bswap_code = 1 at qemu/trarget-arm/translate.c line 11063.

**Closed** 2021-10-03 16:49 UTC
