### ISSUE TITLE
Reuse of Unicorn Instances

### ISSUE THREAD

**Issue by eqv** [unicorn-engine/unicorn#351] opened 2015-12-29 00:33 UTC
Can Unicorn instances be reused after a Start call returned with an error? I am currently Trying to reuse the instances (e.g. running again from a different address), but this seems to lead to inconsistent behavior (e.g. UC_ERR_FETCH_UNMAPPED in the second run at an address that is guaranteed to be mapped, and that is fetched correctly in a third run), even though I reset all mappings / registers. Is this to be expected?

**Comment by lunixbochs** [comment] 2015-12-29 00:35
Sounds like a bug.

**Comment by farmdve** [comment] 2015-12-29 16:32
I have been re-using uc_emu_start many times. Although I've hooked the most important stuff like invalid memory and invalid fetch.

Works for me.

**Comment by aquynh** [comment] 2016-01-01 02:27
if you can reliably reproduce this issue, please send in a testcase.

**Comment by ranmrdrakono** [comment] 2016-01-02 08:46
Unfortunately I can only reproduce this in very long runs. Fixed this by recreating a new unicorn instance after every stop. If I find the time, I will try to construct a minimal example. Would you accept testcases written in Go instead of C?

**Comment by aquynh** [comment] 2016-01-02 10:22
no, please keep testcases in C or Python only.

if your testcase is in Go, just post it, and hopefully somebody can help to rewrite it in C or Python.

**Comment by williballenthin** [comment] 2016-01-11 04:30
I *think* this is also affecting me. Since I haven't yet constructed a minimal test case, you should take the following with the grain of salt, since its just conjecture at this point.

In part of my code, I brute force the emulation of some instructions (to see where jumps and calls go). Occasionally, I end up in nowhere-land. I register a `HOOK_MEM_UNMAPPED` handler to log the events and stop the emulator. When I've detected this case, I reset PC and keep emulating at the next instruction.

*Sometimes* (but not always), the subsequent invocation of `.emu_start` immediately returns with the unmapped memory error code of the previous run. Currently, I handle the bug by retrying the emulation a second time, which seems to (usually?) work.

Again, I could be wrong (it could even be a bug in my code!), but the symptoms sound similar to what OP described.

**Comment by williballenthin** [comment] 2016-01-11 04:59
Added test case demonstrating issue.

**Comment by farmdve** [comment] 2016-01-11 12:38
Please re-write your test in C, so that it is easier for me to trace the code with gdb.

**Comment by williballenthin** [comment] 2016-01-11 14:06
I think you are misreading the test case. The comment `mapped: 0x1000` is intended to show that the `mov` instruction is found at address 0x1000. I can see how you might have understood this to mean that the memory access was to 0x1000, but as you showed, that is not correct.

This test is intended to show that when the emulator is started the second time, after the invalid memory fetch, the emulator raises an exception. Naturally, exceptions are an artifact of Python, but since this also affects my Go code, I suspect the issue is in the underlying C library.

**Comment by farmdve** [comment] 2016-01-11 14:26
As far as my C test went, there were no problems in reusing the instance. I have been re-using the C unicorn instances in my project for a while, not once has it not worked.

**Comment by lunixbochs** [comment] 2016-01-11 14:33
Here's the test in question reproduced with the error in C: https://bochs.info/p/njxvg6

**Comment by williballenthin** [comment] 2016-01-11 14:59
thanks @lunixbochs. i've also just created a PR with a similar test case in C. #368.

**Comment by williballenthin** [comment] 2016-01-11 15:12
Maybe related: why does the first call to `uc_emu_start()` not return with an error when there's an invalid memory access? Would this be the intended behavior?

From reading the documentation (but not the Unicorn source code), it seems that by returning `true` or `false` from the hook handler might affect how the engine decides to continue (though this return value doesn't seem to change the what `uc_emu_start` returns in the test in #368). If the handler returns `true`, what is intended to happen? What if it returns `false`?

My expectation as a potentially new user of the library would be: if `uc_emu_start` does not terminate at the address I requested (or otherwise hit an execution limit, time/insn count), then its return value would signal why.

**Comment by farmdve** [comment] 2016-01-11 16:02
The reason is probably that env->invalid_error is not reset.

**Comment by aquynh** [comment] 2016-01-11 17:08
this is fixed now thanks to a PR of @farmdve. please confirm, thanks.

**Comment by aquynh** [comment] 2016-01-11 17:41
@williballenthin, `uc_emu_start()` returns `uc_err` value, and it always tells you the error code when something is wrong during emulation. if what you get is unexpected, then it is a bug.

**Comment by williballenthin** [comment] 2016-01-11 18:18
fix works for me. thanks @farmdve  @aquynh  @lunixbochs

**Comment by williballenthin** [comment] 2016-01-11 18:19
> Also, currently the software MMU code assumes that if you have a memory event hook, you will always return true, that is, it doesn't check if your hook actually handled the event by say mapping the address or something.

i'll open another issue to track this discussion

**Closed** 2016-01-12 01:07 UTC
Labels: bug

**Comment by aquynh** [comment] 2016-01-12 02:07
@farmdve yes it is best if all the testcases are done with the *unit framework* in tests/unit/. however, since not everybody is familiar with C, Python testcases using *regress framework* in tests/regress/ are also acceptable.

we have an item in the TODO list to rewrite all the C testcases under tests/regress/ to use our *unit framework*. if anybody is still looking for something easy-enough to do, feel free to pick up this.
