### ISSUE TITLE
cmake static build failed to make test

### ISSUE THREAD

**Issue by chfl4gs** [unicorn-engine/unicorn#1285] opened 2020-06-06 16:00 UTC
**Error**
Both 32bit and 64bit are showing the same error. Example can be found [here](https://travis-ci.org/github/unicorn-engine/unicorn/jobs/695298273).
```
make: Entering directory '/home/chflags/Work/test/unicorn/tests/unit'
cc -Wall -Werror -Wno-unused-function -g -D__USE_MINGW_ANSI_STDIO=1 -L ../../ -I ../../include -L ../../cmocka/src -I ../../cmocka/include -L /usr/local/lib -I /usr/local/include    test_hang.c  -pthread -lrt -lcmocka -lunicorn -o test_hang
/usr/bin/ld: ../..//libunicorn.a(uc.c.o): in function `cpu_context_size':
uc.c:(.text+0x103): undefined reference to `M68K_REGS_STORAGE_SIZE'
/usr/bin/ld: uc.c:(.text+0x11f): undefined reference to `ARM_REGS_STORAGE_SIZE_armeb'
/usr/bin/ld: uc.c:(.text+0x13b): undefined reference to `ARM64_REGS_STORAGE_SIZE_aarch64eb'
/usr/bin/ld: uc.c:(.text+0x14b): undefined reference to `X86_REGS_STORAGE_SIZE'
/usr/bin/ld: uc.c:(.text+0x16f): undefined reference to `MIPS64_REGS_STORAGE_SIZE_mips64'
/usr/bin/ld: uc.c:(.text+0x188): undefined reference to `SPARC64_REGS_STORAGE_SIZE'
/usr/bin/ld: uc.c:(.text+0x19b): undefined reference to `ARM64_REGS_STORAGE_SIZE_aarch64'
/usr/bin/ld: uc.c:(.text+0x1af): undefined reference to `MIPS_REGS_STORAGE_SIZE_mips'
/usr/bin/ld: uc.c:(.text+0x1c3): undefined reference to `ARM_REGS_STORAGE_SIZE_arm'
/usr/bin/ld: uc.c:(.text+0x1d3): undefined reference to `SPARC_REGS_STORAGE_SIZE'
/usr/bin/ld: uc.c:(.text+0x1e3): undefined reference to `MIPS_REGS_STORAGE_SIZE_mipsel'
/usr/bin/ld: uc.c:(.text+0x1f3): undefined reference to `MIPS64_REGS_STORAGE_SIZE_mips64el'
/usr/bin/ld: ../..//libunicorn.a(uc.c.o): in function `uc_open':
uc.c:(.text+0x508): undefined reference to `m68k_uc_init'
/usr/bin/ld: uc.c:(.text+0x57d): undefined reference to `arm_uc_init'
/usr/bin/ld: uc.c:(.text+0x5bd): undefined reference to `arm64eb_uc_init'
/usr/bin/ld: uc.c:(.text+0x60b): undefined reference to `mips_uc_init'
/usr/bin/ld: uc.c:(.text+0x621): undefined reference to `mips64_uc_init'
/usr/bin/ld: uc.c:(.text+0x652): undefined reference to `x86_uc_init'
/usr/bin/ld: uc.c:(.text+0x688): undefined reference to `sparc64_uc_init'
/usr/bin/ld: uc.c:(.text+0x703): undefined reference to `arm64_uc_init'
/usr/bin/ld: uc.c:(.text+0x71b): undefined reference to `armeb_uc_init'
/usr/bin/ld: uc.c:(.text+0x72f): undefined reference to `mipsel_uc_init'
/usr/bin/ld: uc.c:(.text+0x745): undefined reference to `mips64el_uc_init'
/usr/bin/ld: uc.c:(.text+0x75b): undefined reference to `sparc_uc_init'
collect2: error: ld returned 1 exit status
make: *** [<builtin>: test_hang] Error 1
make: Leaving directory '/home/chflags/Work/test/unicorn/tests/unit'
````

**Steps to reproduce**
In unicorn root directory, run command below:-
```
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DUNICORN_BUILD_SHARED=OFF .. && make -j8
cp libunicorn.* ../
make -C ../tests/unit test && make -C ../tests/regress test
```

**Comment by aquynh** [comment] 2020-06-06 16:21
@scribam @Johnnynator do you have any comments?

**Comment by Johnnynator** [comment] 2020-06-06 16:59
The problem is, that the cmake build system has the libs split, and `libunicorn.a` does not duplicate the content of `lib*-softmmu.a`:
One possible solution is to only create a single static archive (`libunicorn.a`) and no `lib*-softmmu.a`

**Comment by wtdcode** [comment] 2021-10-03 17:25
Fixed in uc2.

**Closed by wtdcode** 2021-10-03 17:25 UTC

**Comment by edsky** [comment] 2021-10-04 09:26
Where can I find uc2? @wtdcode

**Comment by wtdcode** [comment] 2021-10-04 09:28
> Where can I find uc2? @wtdcode

The dev branch. I fixed the static build long ago.
