### ISSUE TITLE
tcg is generating AVX code on platforms that don't support AVX instruction set and causing #UD exception.

### ISSUE THREAD

**Issue by hzqst** [unicorn-engine/unicorn#1601] opened 2022-04-23 13:41 UTC
**Description**
tcg is generating the following code on platforms that don't support AVX instruction and causing the program termination due to #UD exception (at vzeroupper).
![image](https://user-images.githubusercontent.com/12287588/164898216-e980f709-7ade-41c4-96da-fe9538746635.png)

**How to repro the issue on Windows**
`bcdedit /set xsavedisable 1`,  reboot and run `test_x86.exe`

**How to repro the issue if I don't want to change bcd configs**
get a chip that don't support AVX instruction set. e.g. Intel G4560

**Current unexcepted result** 
multiple unhandled #UD exceptions throwed while running test_x86.exe :
![333](https://user-images.githubusercontent.com/12287588/164901774-0134107e-f6f2-450d-afff-4fe5cbfff3d9.png)

**Excepted result** 
No exceptions shoule be there while running test_x86.exe.

**Version**
2.0.0.rc1 ~ 2.0.0.rc7

**Comment by wtdcode** [comment] 2022-04-23 21:35
Confirmed it's a known bug since AVX1/AVX2 is not correctly detected.

**Comment by LFriede** [comment] 2022-06-10 18:54
Hi, is there a workaround for this? Can I hardcode that detection to compile a working version for my laptop or something?

**Comment by invlpg** [comment] 2022-11-09 02:54
having the same issue, any work around?

**Comment by wtdcode** [comment] 2023-02-07 00:08
Fixed in 3199dd88dee094c3fc456971e5f469c22cb1160d

**Closed by wtdcode** 2023-02-07 00:08 UTC
Labels: bug, enhancement

**Comment by wtdcode** [comment] 2023-09-01 08:03
> > Fixed in [3199dd8](https://github.com/unicorn-engine/unicorn/commit/3199dd88dee094c3fc456971e5f469c22cb1160d)
> 
> did this get merged into master yet? im still having issues with this

Not yet, 2.1.0 still on the way.
