### ISSUE TITLE
ARM CPSR reg update

### ISSUE THREAD

**Issue by McLovi9** [unicorn-engine/unicorn#358] opened 2016-01-04 20:20 UTC
Hi, I'm new to ARM assembly so maybe I messed up something but seems like Current Program Status Register (CPSR) is not updated at all. Its always set to zero.

``` python

from __future__ import print_function
from unicorn import *
from unicorn.arm_const import *


# code to be emulated
ARM_CODE   = "\x00\x00\xa0\xe3"  # start: mov r0, #0
ARM_CODE  += "\x01\x10\xa0\xe3"  # mov r1, #1
ARM_CODE  += "\x00\x00\x50\xe3"  # cmp r0, #0
ARM_CODE  += "\xfb\xff\xff\x1a"  # bne start
#ARM_CODE  += "\x00\x10\xa0\xe1"  # mov r1, r0

# memory address where emulation starts
ADDRESS  = 0x1000


# callback for tracing instructions
def hook_code(uc, address, size, user_data):
    print(">>> Tracing instruction at 0x%x, instruction size = %u" %(address, size))
    print(uc.reg_read(UC_ARM_REG_CPSR))


# Test ARM
def test_arm():
    print("Emulate ARM code")
    try:
        # Initialize emulator in ARM mode
        mu = Uc(UC_ARCH_ARM, UC_MODE_ARM)

        # map 2MB memory for this emulation
        mu.mem_map(ADDRESS, 2 * 1024 * 1024)

        # write machine code to be emulated to memory
        mu.mem_write(ADDRESS, ARM_CODE)

        # initialize machine registers
        mu.reg_write(UC_ARM_REG_R0, 0x0)
        mu.reg_write(UC_ARM_REG_R2, 0x0)
        mu.reg_write(UC_ARM_REG_R3, 0x0)

        # tracing all instructions with customized callback
        mu.hook_add(UC_HOOK_CODE, hook_code)

        # emulate machine code in infinite time
        mu.emu_start(ADDRESS, ADDRESS + len(ARM_CODE))

        # now print out some registers
        print(">>> Emulation done. Below is the CPU context")

        r0 = mu.reg_read(UC_ARM_REG_R0)
        r1 = mu.reg_read(UC_ARM_REG_R1)
        print(">>> R0 = 0x%x" %r0)
        print(">>> R1 = 0x%x" %r1)

    except UcError as e:
        print("ERROR: %s" % e)

if __name__ == '__main__':
    test_arm()


```

**Comment by JCYang** [comment] 2016-01-05 03:39
you should read APSR instead, I don't know whether CPSR work in unicorn, but it's for privilege codes in ARM.

**Comment by McLovi9** [comment] 2016-01-05 08:42
the same issue with APSR is always set to zero

**Comment by aquynh** [comment] 2016-01-05 09:03
@McLovi9, can you please send a pull request to put your above testcase under tests/regress/ directory? thanks.

**Comment by JCYang** [comment] 2016-01-05 09:49
@McLovi9  Your code works well(CPSR is not zero and has changed in the emulation process) in my build. I suggest you use the latest git codes, and modify your python code to print out hex can better read the register.

sorry that I forget that it is APSR not working correctly in unicorn, you can read CPSR

**Comment by JCYang** [comment] 2016-01-05 09:58
one caveat: if you intend to read cpu regs from unicorn, it's ok in hook code(value correct, if you find something wrong, please file a bug), but outside it, PC/EIP and any program counter on all CPU archs supported may be wrong. That is, outside hook code, don't count on the PC value you read from uc.reg_read().
This is a limitation right now, I don't know whether we should/could fix it in the future, because it's not trivial a task, and may lead to significant performance penalty.

**Comment by McLovi9** [comment] 2016-01-05 10:34
@JCYang @aquynh I just got the latest code from github and it works CPSR is not zero, so no need for testcase. Thanks.

I only read registers in the hook code function. I don't plan to read the registers when the emulation is running, makes no sens since its volatile data. You cant do it with debugger running so its OK for me, but just like with debuggers it would be great to have some API break_emul, suspend_emul to call from outside of hook code and get the last PC / thread context. In this case the user can decide how often he wants to get an update / query the context and change it from there.

**Comment by McLovi9** [comment] 2016-01-05 10:41
@JCYang I forgot CPSR reg write 

    def hook_code(uc, address, size, user_data):
     print(">>> Tracing instruction at 0x%x, instruction size = %u" %(address, size))
     print(uc.reg_read(UC_ARM_REG_CPSR))
     uc.reg_write(UC_ARM_REG_CPSR, 0)

is not working from hook function ?  limitation ?

**Comment by aquynh** [comment] 2016-01-05 16:51
but exactly what is not working?

**Comment by aquynh** [comment] 2016-01-05 16:52
@JCYang: no, you should be able to read registers from inside hook callback or outside. if you fail to do that, it is a bug and should be reported.

**Comment by McLovi9** [comment] 2016-01-05 17:47
@aquynh what is wrong is that in this case 
    uc.reg_write(UC_ARM_REG_CPSR, 0)

has no effect, the register value is not changed.

**Comment by JCYang** [comment] 2016-01-06 02:05
@aquynh I should described that more precisely and correct some wrong wording in my last post.
We can read PC(via uc.reg_read()) anywhere we like, for example, when the emulation is stop.
but the PC is probably wrong. Because TCG‘s mechanism only update PC when switching TB. If we stop at the middle of one TB, and read the PC, it's wrong. 
And I should correct that, not even in hook code we should read the PC, it's wrong there too. But in hook code, we can use the address argument, which is the correct PC to serve our purpose.

@McLovi9 Yes, writing to CPSR is not supported at the moment. I will try to provide a patch ASAP.

**Comment by aquynh** [comment] 2016-01-06 02:15
@JCYang, as i said, if your PC value is wrong **anywhere**, that is a bug and should be fixed. please send a pull request to put your testcase under `tests/`, thanks.

**Comment by JCYang** [comment] 2016-01-06 03:55
@aquynh because update PC after every instruction is not *required* by TCG in the middle of one TB, when TCG translator need pc value(for example, the LDR relative to PC), it will read pc value from the disambler context(DisasContext). And for most user, read PC outside hook code is not a considered usage scenario(may even make no sense), and introducing codes to do so(TCG ops to write back PC after each instruction) will incur non trivial performance penalty. Combine all the reason above, I am still hesitate whether we should fix it, I suggest we should document this as limitation, while probably no one need it~
Correct myself:
PC read from within hook code is correct, because unicorn sync it before call the hook.
testcase is very simple,  PC read after emulation done are probably wrong, unless the point you stop is a start of a TB.

**Comment by JCYang** [comment] 2016-01-06 03:58
Err...  maybe we can just call uc->set_pc() just like when there's hook? this seems like a pretty cheap fix.

**Comment by aquynh** [comment] 2016-01-06 04:01
i am well aware of the situation you mentioned, and already fixed this issue for x86 long ago. at the moment, for x86, you should be able to read PC & also other registers anywhere anytime. if the value is unexpected, then that is a bug.

i think i havent done this for ARM and other archs yet, so this should be fixed too.

testcase might be simple, but still very important to have - to avoid future regression.

**Comment by neobrain** [comment] 2016-06-19 12:08
> @aquynh what is wrong is that in this case
>     uc.reg_write(UC_ARM_REG_CPSR, 0)
> has no effect, the register value is not changed.

&nbsp;
> @McLovi9 Yes, writing to CPSR is not supported at the moment. I will try to provide a patch ASAP.

@JCYang Any update on that patch? I just ran into this in a project of mine, and I'm not sure how to deal with this without being able to rely on `uc.reg_write`.

(also, this issue report has become somewhat convoluted - maybe we should create a new issue report about `uc.reg_write` not working for `UC_ARM_REG_CPSR`?)

**Comment by aquynh** [comment] 2017-01-05 03:37
i just merged the PR https://github.com/unicorn-engine/unicorn/pull/707, and now it cs_reg_write() can write to CPSR. please report if you still have issues.

**Closed by aquynh** 2017-01-05 03:37 UTC
Labels: bug
