### ISSUE TITLE
uc_hook_add with UC_HOOK_INSN not working

### ISSUE THREAD

**Issue by metal-crow** [unicorn-engine/unicorn#541] opened 2016-05-04 02:43 UTC
Like it sounds, when I open the [example](https://github.com/unicorn-engine/unicorn/blob/master/samples/sample_x86.c) (via the visual studio MSVC project), and compile it, all code works, but any hook that uses UC_HOOK_INSN to hook on a specific instruction does not trigger.

Replacing the line with `uc_hook_add(uc, &trace1, UC_HOOK_BLOCK, hook_syscall, NULL, 1, 0);` generates the trigger fine, so i believe this is an error with UC_HOOK_INSN.

Alternatively, the sample code could be incorrect.

**Comment by aquynh** [comment] 2016-05-04 02:50
> Replacing the line with uc_hook_add(uc, &trace1, UC_HOOK_BLOCK, hook_syscall, NULL, 1, 0); generates the trigger fine, so i believe this is an error with UC_HOOK_INSN.

exactly which line do you mean?

**Comment by metal-crow** [comment] 2016-05-04 02:53
Any line that uses the `uc_hook_add` function with the `UC_HOOK_INSN` argument (see [here](https://github.com/unicorn-engine/unicorn/blob/master/samples/sample_x86.c#L808) and [here](https://github.com/unicorn-engine/unicorn/blob/master/samples/sample_x86.c#L642)). Replacing those (changing `UC_HOOK_INSN` to `UC_HOOK_BLOCK` and removing the type of instruction to hook on), results in the hook function being called normally.

**Comment by aquynh** [comment] 2016-05-04 03:03
this is a bug, and should be fixed so you dont need workaround like that.

can you modify this line https://github.com/unicorn-engine/unicorn/blob/master/bindings/msvc/unicorn_dynload.c#L248 to:

    va_start(valist, end);

then compile again to see the problem is fixed?

**Comment by metal-crow** [comment] 2016-05-04 03:09
No, still didn't trigger the hook.

**Comment by aquynh** [comment] 2016-05-04 03:20
@xorstream, can you look at this issue with the MSVC binding?

i think the bug is there at that line with `va_start()` because we changed the API uc_hook_add() with this commit https://github.com/unicorn-engine/unicorn/commit/a7a1dcc66128801d1ef82e992a6cc4ff10fcce5d. but it seems there are still other issues to be fixed for UC_HOOK_INSN :-?

**Comment by xorstream** [comment] 2016-05-10 13:37
The change to "va_start(valist, end)" does fix this problem.

@metal-crow please check that your exe file is loading an up to date version of unicorn.dll.
While testing I noticed that initially the fix didn't work for me, but it was due to an old version of unicorn.dll being loaded. The file "unicorn\bindings\msvc\readme.txt" should help you work out what unicorn.dll is being loaded by a project that is executed inside of MSVC.

**Closed** 2016-05-10 13:55 UTC

**Comment by aquynh** [comment] 2016-05-10 14:03
the fix from @xorstream was merged. please report if you still have this issue.
