### ISSUE TITLE
sample_arm fails in thumb mode? 

### ISSUE THREAD

**Issue by disektor** [unicorn-engine/unicorn#638] opened 2016-09-16 02:15 UTC
I am new to Unicorn.  When I run the sample_arm example, the ARM mode works but thumb mode seems to fail (Failed on uc_emu_start() with error returned: 8,  and the register value in SP is wrong).

Did I miss anything?

Here is the full output:

unicorn/samples$ ./sample_arm
Emulate ARM code
>>> Tracing basic block at 0x10000, block size = 0x8
>>> Tracing instruction at 0x10000, instruction size = 0x4
>>> Emulation done. Below is the CPU context
>>> R0 = 0x37
>>> R1 = 0x3456

==========================

Emulate THUMB code
>>> Tracing basic block at 0x10000, block size = 0x0
>>> Tracing instruction at 0x10000, instruction size = 0x4
>>> Tracing basic block at 0x10400, block size = 0x0
...
Failed on uc_emu_start() with error returned: 8
>>> Emulation done. Below is the CPU context
>>> SP = 0x1234

**Comment by aquynh** [comment] 2016-09-18 01:39
are you using the latest code from Github?

**Comment by disektor** [comment] 2016-09-18 02:50
Yes, a fresh clone from git on a x86_64,  Ubuntu 14.04.4 system.
Here is the uname and git status info.

~/unicorn/unicorn$ uname -a
Linux R320 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

~/unicorn/unicorn$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

**Comment by disektor** [comment] 2016-09-18 02:54
Just checked out another copy.  Same behavior with sample_arm (good with ARM, but failure in thumb mode)

~/unicorn/unicorn$ ./samples/sample_arm
Emulate ARM code
>>> Tracing basic block at 0x10000, block size = 0x8
>>> Tracing instruction at 0x10000, instruction size = 0x4
>>> Emulation done. Below is the CPU context
>>> R0 = 0x37
>>> R1 = 0x3456

==========================

Emulate THUMB code
>>> Tracing basic block at 0x10000, block size = 0x0
>>> Tracing instruction at 0x10000, instruction size = 0x4
>>> Tracing basic block at 0x10400, block size = 0x0
... ...
>>> Tracing basic block at 0x20fc00, block size = 0x0
Failed on uc_emu_start() with error returned: 8
>>> Emulation done. Below is the CPU context
>>> SP = 0x1234


~/unicorn/unicorn$ git log | more
commit 5af4880f1a459fc152e3e0e1ac99d9915575350d
Merge: d59081b 3bc55f9
Author: Nguyen Anh Quynh <aquynh@gmail.com>
Date:   Fri Sep 16 23:23:59 2016 +0700

    Merge pull request #637 from lukenels/haskell-fix
    
    Relax transformers constraint for haskell bindings for GHC 8

commit 3bc55f9568400301f5693f7f509a8e01ec447849
Author: Luke Nelson <lukenels@cs.washington.edu>
Date:   Thu Sep 15 19:04:18 2016 -0700

    Relax transformers constraint for haskell bindings for GHC 8

... ...

**Comment by aquynh** [comment] 2016-09-18 03:37
This worked before. Can you "git bisect" to find which commit causes this issue?

**Comment by ekse** [comment] 2016-09-18 06:16
This is the commit were the tests started to fail:
https://github.com/unicorn-engine/unicorn/commit/a59f54ca72020833c71f834d41ba30ad4b8061e1

**Comment by aquynh** [comment] 2016-09-18 15:42
@esanfelix, this is related to your PR before, could you look at that?

**Comment by esanfelix** [comment] 2016-09-19 12:31
Sorry for the delays, I've been kind of unavailable for a while. 

I didn't test the sample when I pushed that commit because I was traveling without much free time, and once it was merged I assumed it was all ok.

This issue appears because ARM modes are now handled in a similar way to what the CPU does: bit 0 is used to detect the mode, rather than the mode provided at instantiation time.

The sample_arm file does actually try to emulate THUMB code by using ADDRESS, set to 0x1000. Since bit 0 is 0, this is emulated in ARM mode instead. Setting the address to 0x1000|1 should fix this.

Now, the question is whether we want it this way or want to go back to the previous way? If you ask me, the current way is more accurate and closer to what actual ARM hardware does, so I'd prefer it this way.

If you agree, I can push a change to the sample file to fix it. This seems to be the expected behavior:

```
Emulate ARM code
>>> Tracing basic block at 0x10000, block size = 0x8
>>> Tracing instruction at 0x10000, instruction size = 0x4
>>> Emulation done. Below is the CPU context
>>> R0 = 0x37
>>> R1 = 0x3456
==========================
Emulate THUMB code
>>> Tracing basic block at 0x10000, block size = 0x2
>>> Tracing instruction at 0x10000, instruction size = 0x2
>>> Emulation done. Below is the CPU context
>>> SP = 0x1228
```

With just a simple patch:

```
diff --git a/samples/sample_arm.c b/samples/sample_arm.c
index 2c69ce6..3c79493 100644
--- a/samples/sample_arm.c
+++ b/samples/sample_arm.c
@@ -135,7 +135,7 @@ static void test_thumb(void)

     // emulate machine code in infinite time (last param = 0), or when
     // finishing all the code.
-    err = uc_emu_start(uc, ADDRESS, ADDRESS + sizeof(THUMB_CODE) -1, 0, 0);
+    err = uc_emu_start(uc, ADDRESS | 1, ADDRESS + sizeof(THUMB_CODE) -1, 0, 0);
     if (err) {
         printf("Failed on uc_emu_start() with error returned: %u\n", err);
     }
```

**Comment by aquynh** [comment] 2016-09-19 12:36
do you want to send a pull req for this?

**Comment by ekse** [comment] 2016-09-20 04:33
@esanfelix I think the new approach makes more sense and the tests should be changed to reflect that. That's what I just did for my rust bindings.

**Comment by esanfelix** [comment] 2016-09-20 08:33
I've pushed it now, two commits one with sample_arm.c and one with sample_arm.py once I realized it needed to be changed there too.

The Java, Go and Ruby bindings also need the same changes, but I don't have them set up and I'd rather have someone try that before committing.

Btw I'm not sure both commits made it to the pull request (not a heavy GitHub user so might have screwed up) so let me know if something is wrong.

**Comment by aquynh** [comment] 2016-09-20 12:08
i merged https://github.com/unicorn-engine/unicorn/pull/639, and this is fixed now, thanks!

**Closed** 2016-09-20 12:07 UTC

**Comment by aquynh** [comment] 2016-09-20 12:19
@sashs & @cseagle: i fixed your Ruby & Java samples in this commit: https://github.com/unicorn-engine/unicorn/commit/95e8dc0fb845bfe0812fe855a4064a05dc74ac1d. if you find something wrong, please let me know.

@lunixbochs & @adrianherrera: i am not confident with Go & Haskell samples, so please send pull req to fix address of Thumb samples, thanks!

**Comment by sashs** [comment] 2016-09-20 19:25
Hi, looks good. :)

**Comment by adrianherrera** [comment] 2016-09-21 07:51
PR made. See PR #641
