### ISSUE TITLE
Is unicorn messing up signal handling?

### ISSUE THREAD

**Issue by HclX** [unicorn-engine/unicorn#945] opened 2018-02-18 07:14 UTC
I'm trying to stop an emulation using ctrl+c and found it doesn't work, not sure if this is something messed up by the emulation. Here is a minimal test case:
```python
#!/usr/bin/env python
from __future__ import print_function
from unicorn import *
from unicorn.arm64_const import *
import sys
import signal

# code to be emulated: movz x0, #0x1000; br x0 (dead loop)
ARM64_CODE = b"\x00\x00\x82\xd2\x00\x00\x1f\xd6"

# memory address where emulation starts
ADDRESS    = 0x1000

# Test ARM64
def test_arm64():
    print("Emulate ARM64 code")
    try:
        # Initialize emulator in ARM mode
        mu = Uc(UC_ARCH_ARM64, UC_MODE_ARM)

        # map 2MB memory for this emulation
        mu.mem_map(ADDRESS, 2 * 1024 * 1024)

        # write machine code to be emulated to memory
        mu.mem_write(ADDRESS, ARM64_CODE)

        # emulate machine code in infinite time
        mu.emu_start(ADDRESS, ADDRESS + len(ARM64_CODE))
    except UcError as e:
        print("ERROR: %s" % e)

def ctrl_c_handler(sig, frame):
    logging.info("User interrupted")
    sys.exit(0)
        
if __name__ == '__main__':
    signal.signal(signal.SIGINT, ctrl_c_handler)
    test_arm64()
```

**Comment by r0ptr** [comment] 2022-03-06 16:25
I seem to ran into this issue, why was it closed without any explanation? as far as I can tell, once `emu_start` is called, there's no way to stop unicorn with control + c (unless it stops itself i.e. finishes execution)

**Comment by wtdcode** [comment] 2022-05-06 21:40
> I seem to ran into this issue, why was it closed without any explanation? as far as I can tell, once `emu_start` is called, there's no way to stop unicorn with control + c (unless it stops itself i.e. finishes execution)

@r0ptr This is intended behavior from python [sigal modules.](https://docs.python.org/3.10/library/signal.html)

> A long-running calculation implemented purely in C (such as regular expression matching on a large body of text) may run uninterrupted for an arbitrary amount of time, regardless of any signals received. The Python signal handlers will be called when the calculation finishes.

A quick workaround is start a new thread for unicorn:

```python
#!/usr/bin/env python
from __future__ import print_function
from unicorn import *
from unicorn.arm64_const import *
import sys
import signal
import logging
import threading

# code to be emulated: movz x0, #0x1000; br x0 (dead loop)
ARM64_CODE = b"\x00\x00\x82\xd2\x00\x00\x1f\xd6"

# memory address where emulation starts
ADDRESS    = 0x1000

# Test ARM64
def test_arm64():
    print("Emulate ARM64 code")
    try:
        # Initialize emulator in ARM mode
        mu = Uc(UC_ARCH_ARM64, UC_MODE_ARM)

        # map 2MB memory for this emulation
        mu.mem_map(ADDRESS, 2 * 1024 * 1024)

        # write machine code to be emulated to memory
        mu.mem_write(ADDRESS, ARM64_CODE)

        # emulate machine code in infinite time
        mu.emu_start(ADDRESS, ADDRESS + len(ARM64_CODE))
    except UcError as e:
        print("ERROR: %s" % e)

def ctrl_c_handler(sig, frame):
    logging.info("User interrupted")
    sys.exit(0)

        
if __name__ == '__main__':
    signal.signal(signal.SIGINT, ctrl_c_handler)
    threading.Thread(target= test_arm64).start()

    while True:
        pass
```

**Comment by wtdcode** [comment] 2022-05-07 11:43
Closed due to wontfix.

**Closed by wtdcode** 2022-05-07 11:43 UTC
Labels: invalid, wontfix
