### ISSUE TITLE
roadmap to Qemu 2.5 syncing

### ISSUE THREAD

**Issue by aquynh** [unicorn-engine/unicorn#461] opened 2016-03-14 03:26 UTC
i wanted to straightly upgrade to Qemu 2.5, but there is a lot of code changed from Qemu 2.2.1, which Unicorn is based on.

therefore, i will break this down in few phases to make it more manageable, and also easier to track bugs introduced by this task:
- upgrade to 2.3.1
- upgrade to 2.4.1
- upgrade to 2.5

expect more update on this work later.

**Comment by egberts** [comment] 2016-03-14 13:49
During my code analysis for porting, I also noticed that incremental porting might be the easier approach because there are many good fixes in Unicorn over QEMU 2.5.

**Comment by lunixbochs** [comment] 2016-04-08 04:41
how much work has been done on this?

**Comment by lunixbochs** [comment] 2016-04-08 16:02
Alright, I'm in the process of cowboy-porting Unicorn directly to qemu 2.5.1 here - https://github.com/lunixbochs/qemu-2.5-unicorn

**Comment by aquynh** [comment] 2016-04-08 16:06
i have been working on this, but slow due to other works.

this is awesome, but frankly i would prefer to break it into smaller steps: to 2.3.1, then 2.4, then 2.5. it is much easier to verify the correctness of porting this way. directly porting to 2.5 is possible, but very prone to errors and also very hard to debug.

what do you think?

**Comment by aquynh** [comment] 2016-04-08 16:08
i also mean by breaking this, the PRs to be reviewed are also much smaller, thus faster to be merged. the change between 2.2 & 2.5 is too much, so reviewing process may take very long.

**Comment by lunixbochs** [comment] 2016-04-08 16:16
Not really my problem here. I'm pretty confident in my porting strategy (and some of my choices will honestly make it much easier to review than 3 manual version bumps, which -face it- if you're not done porting to 2.3 yet this won't happen for quite a while... I spent around 9 hours on this yesterday).

I also have some of the most complex Unicorn test cases with Usercorn (yay running real software), and I don't even really need this merged upstream to use it. I think we'll have no shortage of people interested in this to review/help with the merge anyway. I'm pretty sure based on some of the QEMU 2.5 code that's been flying past this also has some nice performance improvements over 2.2.

(Also you've been previously conservative enough about reviewing/merging much simpler PRs like #481 to the point where I'm already operating on a local fork.)

**Comment by aquynh** [comment] 2016-04-08 16:20
yes bigger PR will naturally get more time to review, because we wont want to unstable the existing code.

sorry about #485 and #481, i am too busy recently. will do it this weekend.

**Comment by lunixbochs** [comment] 2016-04-09 23:53
mostly finished with tcg, tcg/i386, root code, and target-arm

**Comment by lunixbochs** [comment] 2016-04-12 11:46
@aquynh is all the commented out timer stuff in Unicorn's fork important?

**Comment by aquynh** [comment] 2016-04-12 12:46
in general no, but which code is that?

**Comment by lunixbochs** [comment] 2016-04-12 13:00
qemu/hw/mips/cputimer.c and qemu/target-arm/cpu.c

**Comment by lunixbochs** [comment] 2016-04-12 21:30
I'm mostly wondering if they should be fixed, or if the supporting timer code should be removed - because a quick check didn't show any other real uses of the timer.

**Comment by aquynh** [comment] 2016-04-13 17:14
those timers are not important for Unicorn, and can be removed.

**Comment by lunixbochs** [comment] 2017-05-04 23:59
QEMU is now at 2.9. I think we need a better way of updating Unicorn.

**Comment by maximumspatium** [comment] 2018-05-04 15:44
> QEMU is now at 2.9.

By now, QEMU is at 2.12.0 that decreases the chances that these two projects will get synchronized someday.

> I think we need a better process for updating Unicorn.

I agree. Back in 2015, Unicorn has been created by means of patching the QEMU codebase to remove unnecessary stuff (HW emulation, GDB and KVM support), to make it thread-safe and to add hooks for debugging/monitoring virtual execution.

To my understanding, the problem is that no documentation/tools on how to hack QEMU code have been publicly released. I assume that the initial patching was done by hand **which isn't future-proof**. Everyone that want to hack Unicorn need to spend weeks/months to work through thousands of lines of macro-convoluted C code to grasp the differences. That's probably one of the major reasons why it's difficult to find volunteers for adding support for other CPUs than x86 & ARM (that are widely supported anyway by several other tools). Recall: support for 18 archs initially planned, only 6 actually supported.

Syncing with QEMU development requires even more effort (and manual work) because 

- QEMU has been heavily refactored since 2.2.1 (2015)
- Unicorn incorporated several security and CPU emulation fixes that didn't reached the upstream

So we're apparently back to the initial axiom:

_No light at the end of the dark tunnel_

unless we'll get better roadmap/docs/tools etc.

**Comment by aquynh** [comment] 2018-05-08 02:50
somebody from community already ported Unicorn to new Qemu version 2.11, at
https://github.com/yuzu-emu/unicorn

this focused mostly on Arm64 at the moment.

**Comment by aquynh** [comment] 2018-05-09 14:11
ping @lioncash, the author of that Unicorn port to Qemu 2.11

**Comment by anatol** [comment] 2019-03-04 01:43
Any updates here? Unicorn still uses ancient version of QEMU. It needs to be moved to 3.1.0.

**Comment by aquynh** [comment] 2019-03-04 01:59
you can help to review & fix bugs in https://github.com/unicorn-engine/unicorn/pull/1046

**Comment by bencoman** [comment] 2019-11-27 21:54
What is the feasibility of backporting to QEMU?  Maybe supported by GoFundMe or similar?

**Comment by aquynh** [comment] 2019-11-28 01:45
I have been thinking about starting "Unicorn2", that sync with latest Qemu
version. I am aware that big companies have been using Unicorn, and the
number of really cool projects depending on it is growing.


This takes a lot of time & effort, but am not sure Gofundme is the right
way to get fund, or better to find some sponsors from other sources.


Any ideas?

**Comment by lunixbochs** [comment] 2019-11-28 01:53
If you do a unicorn2, please don't hand port it again, please use some kind of scripts to automatically refactor qemu :)

**Comment by aquynh** [comment] 2019-11-28 01:58
That would involve a lot of super advanced auto src code analysis, which is never possible. You know that right :-)

Perhaps with another approach to make it much easier to maintain.

**Comment by lunixbochs** [comment] 2019-11-28 02:04
You don't need to auto analyze the source. Automatic here just means "instead of using a regex in my editor to add an arg to localize TCG 9000 times, I use a script to do it once".

Then if it breaks you just need to update the script.

**Comment by aquynh** [comment] 2019-11-28 02:16
Yes for some code you can do that, but not all. Still there are a lot of
manual work.

**Comment by lunixbochs** [comment] 2019-11-28 02:16
I updated my comment with a more specific outline.

**Comment by egberts** [comment] 2019-11-28 15:42
So, full force is behind https://github.com/yuzu-emu/unicorn/network ?

**Comment by lunixbochs** [comment] 2019-11-28 16:11
I think the issue with yuzu is they only care about one target so everything else is broken

**Comment by egberts** [comment] 2019-11-28 19:02
I’m curious if that Yuzu QEMU has done anything to make it into two components:classes such like engine and API.

**Closed** 2021-10-03 16:50 UTC
Labels: TODO
